### ISSUE TITLE
Containerize Project with Docker

### ISSUE THREAD

**Issue by NolanTrem** [emrgnt-cmplxty/automata#285]
**Description**:

This issue outlines the proposed steps for containerizing the Automata Project using Docker. This containerization would allow for increased portability and a simplified deployment process.

## Requirements:
* Docker
* Docker-compose (if we plan to use multi-container setup)

## Steps:

1. **Create a Dockerfile**: This file is the blueprint for building the Docker image for the Automata project. It should contain all the necessary steps to set up the environment and the project itself.

Sample Dockerfile:

```Dockerfile
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME Automata

# Run app.py when the container launches
CMD ["python", "app.py"]
```

2. **Build the Docker image**: The Docker image can be built using the Dockerfile created in the previous step.

Sample command:

```shell
docker build -t automata .
```

3. **Create a docker-compose file**: If the Automata project has dependencies on other services such as databases, we might need a docker-compose file to manage multiple containers.

Sample docker-compose.yml:

```yml
version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
```

4. **Push the Docker image to Docker Hub or any other Docker registry**: This step will make the Docker image accessible to anyone who wants to run the Automata project. 

Sample command:

```shell
docker push automata
```

5. **Update the README.md file**: The README.md file should be updated to include instructions on how to run the Docker image. 

6. **Implement CI/CD pipeline (Optional)**: If we want to automate the build and deployment process, we can use GitHub Actions, Jenkins, or any other CI/CD tool to build the Docker image and push it to Docker Hub whenever changes are pushed to the main branch.

- [x] ~Install Docker and Docker-compose on the development machine.~ Completed by @Exarchias in #286 
- [x] ~Write a Dockerfile for the Automata project.~ Completed by @Exarchias in #286 
- [x] ~Test the Dockerfile.~ Completed by @Exarchias in #286 
- [x] ~If necessary, write a Docker-compose file.~
- [ ] Update the README.md file with instructions on how to use the Docker image.
- [ ] Set up a CI/CD pipeline to automate the Docker build and push process when changes are made to the project.

**Comment by Exarchias** [comment]
Thank you @NolanTrem!
